/**
 * Gallery builder. Turns the formats directory into `site/gallery.json` plus the
 * preview media the page needs.
 *
 * Ranking rule, applied here and nowhere else: measured formats first, ordered by
 * mean percentage of the clip watched; untested formats after them, alphabetically.
 * Losers are not dropped — a format that measured badly is the most useful row in
 * the table, and it keeps its numbers.
 */
import fs from "node:fs";
import path from "node:path";

import { OUT_DIR, ROOT, SITE_DIR, rel } from "./paths.js";
import { loadAllFormats, type LoadedFormat } from "./format.js";

export interface GalleryCard {
  slug: string;
  name: string;
  family: string;
  hypothesis: string;
  useWhen: string;
  avoidWhen?: string;
  tags: string[];
  durationSec: number;
  fps: number;
  variantId: string;
  n: number;
  status: string;
  platforms: string[];
  hook3s: number | null;
  avgViewedPct: number | null;
  viewsPerHour: number | null;
  vsBaselinePct: number | null;
  retention: Array<{ t: number; p: number }>;
  notes?: string;
  updated?: string;
  media: { mp4?: string; webm?: string; poster?: string };
}

export interface Gallery {
  generatedAt: string;
  totals: {
    formats: number;
    measured: number;
    untested: number;
    samples: number;
    platforms: string[];
  };
  cards: GalleryCard[];
}

function rank(a: GalleryCard, b: GalleryCard): number {
  const am = a.status === "measured" && a.avgViewedPct !== null;
  const bm = b.status === "measured" && b.avgViewedPct !== null;
  if (am !== bm) return am ? -1 : 1;
  if (am && bm) {
    const d = (b.avgViewedPct ?? 0) - (a.avgViewedPct ?? 0);
    if (Math.abs(d) > 1e-9) return d;
    return (b.hook3s ?? 0) - (a.hook3s ?? 0);
  }
  return a.slug.localeCompare(b.slug);
}

function copyMedia(fmt: LoadedFormat, mediaDir: string): GalleryCard["media"] {
  const media: GalleryCard["media"] = {};
  const src = path.join(OUT_DIR, fmt.slug);
  const pairs: Array<[string, string, keyof GalleryCard["media"]]> = [
    ["preview.mp4", `${fmt.slug}.mp4`, "mp4"],
    ["preview.webm", `${fmt.slug}.webm`, "webm"],
    ["poster.jpg", `${fmt.slug}.jpg`, "poster"],
  ];
  for (const [from, to, key] of pairs) {
    const f = path.join(src, from);
    if (fs.existsSync(f)) {
      fs.copyFileSync(f, path.join(mediaDir, to));
      media[key] = `previews/${to}`;
    }
  }
  return media;
}

export function buildSite(): Gallery {
  const mediaDir = path.join(SITE_DIR, "previews");
  fs.mkdirSync(mediaDir, { recursive: true });

  const formats = loadAllFormats();
  const cards: GalleryCard[] = formats.map((f) => ({
    slug: f.slug,
    name: f.meta.name || f.slug,
    family: String(f.meta.family ?? "unknown"),
    hypothesis: f.meta.hypothesis ?? "",
    useWhen: f.meta.useWhen ?? "",
    avoidWhen: f.meta.avoidWhen,
    tags: f.meta.tags ?? [],
    durationSec: f.spec.canvas.durationSec,
    fps: f.spec.canvas.fps,
    variantId: f.variantId,
    n: f.data.n,
    status: f.data.status,
    platforms: f.data.platforms ?? [],
    hook3s: f.data.hook3s ?? null,
    avgViewedPct: f.data.avgViewedPct ?? null,
    viewsPerHour: f.data.viewsPerHour ?? null,
    vsBaselinePct: f.data.vsBaselinePct ?? null,
    retention: f.data.retention ?? [],
    notes: f.data.notes,
    updated: f.data.updated,
    media: copyMedia(f, mediaDir),
  }));

  cards.sort(rank);

  const measured = cards.filter((c) => c.status === "measured" && c.n > 0);
  const gallery: Gallery = {
    generatedAt: new Date().toISOString(),
    totals: {
      formats: cards.length,
      measured: measured.length,
      untested: cards.length - measured.length,
      samples: cards.reduce((s, c) => s + c.n, 0),
      platforms: [...new Set(cards.flatMap((c) => c.platforms))].sort(),
    },
    cards,
  };

  fs.writeFileSync(path.join(SITE_DIR, "gallery.json"), JSON.stringify(gallery, null, 2) + "\n", "utf8");

  writeFormatIndex(formats);

  const withMedia = cards.filter((c) => c.media.mp4 || c.media.webm).length;
  console.log(`\n▸ gallery built  ${rel(path.join(SITE_DIR, "gallery.json"))}`);
  console.log(`  ${cards.length} formats · ${measured.length} measured · ${gallery.totals.samples} samples`);
  console.log(`  ${withMedia}/${cards.length} have rendered previews`);
  if (withMedia < cards.length) console.log(`  run \`kw render --all\` to fill the gaps\n`);
  else console.log("");

  return gallery;
}

/**
 * The format index the skill reads. Generated by `kw site build` from meta.yml
 * and data.yml, so the documentation can never drift from the library.
 */
function writeFormatIndex(formats: LoadedFormat[]): void {
  const byFamily = new Map<string, LoadedFormat[]>();
  for (const f of formats) {
    const key = String(f.meta.family ?? "unknown");
    if (!byFamily.has(key)) byFamily.set(key, []);
    byFamily.get(key)!.push(f);
  }

  const pct = (v: number | null | undefined) =>
    v === null || v === undefined ? "—" : `${(v * 100).toFixed(0)}%`;
  const oneLine = (v: string | undefined) => (v ?? "").replace(/\s+/g, " ").trim();

  const measured = formats.filter((f) => f.data.status === "measured").length;
  const samples = formats.reduce((sum, f) => sum + f.data.n, 0);

  const out: string[] = [
    "# The format library",
    "",
    "Generated by `kw site build` from `formats/*/meta.yml` and `data.yml`. Do not edit by hand.",
    "",
    `${formats.length} formats · ${measured} measured · ${samples} samples total`,
    "",
    "`n` is the number of published videos behind a row. `n = 0` means untested —",
    "a valid state, not a gap to paper over.",
    "",
  ];

  for (const [family, list] of [...byFamily].sort((a, b) => a[0].localeCompare(b[0]))) {
    const sorted = [...list].sort((a, b) => a.slug.localeCompare(b.slug));
    out.push(`## ${family}`, "");
    out.push("| Format | n | avg viewed | hook @3s | Hypothesis |");
    out.push("|---|---|---|---|---|");
    for (const f of sorted) {
      out.push(
        `| \`${f.slug}\` | ${f.data.n} | ${pct(f.data.avgViewedPct)} | ` +
          `${pct(f.data.hook3s)} | ${oneLine(f.meta.hypothesis)} |`
      );
    }
    out.push("");
    for (const f of sorted) {
      out.push(`**\`${f.slug}\`** — ${f.meta.name}  `);
      out.push(`Use when: ${oneLine(f.meta.useWhen)}  `);
      if (f.meta.avoidWhen) out.push(`Avoid when: ${oneLine(f.meta.avoidWhen)}  `);
      out.push(`${f.spec.canvas.durationSec}s · ${f.spec.canvas.fps}fps · \`${f.variantId}\``);
      out.push("");
    }
  }

  fs.writeFileSync(
    path.join(ROOT, "skills", "keepwatching", "references", "formats.md"),
    out.join("\n"),
    "utf8"
  );
}
